### ISSUE TITLE
Compress images uploaded by Wagtail

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/consumerfinance.gov#2194] opened 2016-06-16 15:20 UTC
Related to #2175, we should look into doing lossless compression on images uploaded by wagtail.

**Comment by anselmbradford** [comment] 2017-08-10 17:01
@chosak do you know if this was implemented?

**Comment by chosak** [comment] 2017-08-10 17:08
@anselmbradford not that I know of. Wagtail does support compression of images in templates, but we're not using that anywhere as far as I know.

**Comment by anselmbradford** [comment] 2017-08-10 18:17
Thanks!

**Comment by PMARINA** [comment] 2020-07-30 00:38
@chosak Is this still needed or can this be closed?

**Comment by cwdavies** [comment] 2021-05-26 23:08
Closing this issue as it is a duplicate of CFGOV/platform/issues/4041

**Closed by cwdavies** 2021-05-26 23:08 UTC
Labels: Back-end, [effort] medium, [skill-level] intermediate, code.gov, help wanted, wagtail
